swagger: '2.0'
info:
  description: "[webrtc-signal-http](https://github.com/bengreenier/webrtc-signal-http) heartbeat timeout extension
    \n
    ![logo
    gif](https://github.com/bengreenier/webrtc-signal-http-heartbeat/raw/master/readme_example.gif)
    \n\n
    This adds an additional signal message to help prevent stale peers appearing as legitimate, by requiring clients to send this message at a defined interval. Clients that stop sending the message are removed from the [PeerList](https://github.com/bengreenier/webrtc-signal-http#peerlist)."
  version: 1.0.0
  title: webrtc-signal-http-heartbeat
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
schemes:
  - http
paths:
  /heartbeat:
    get:
      summary: Indicates a peer is still actively connected and able to signal
      description: >-
        This endpoint is expected to be called at an interval defined by the extension (default `30s`). The response will be empty.
      operationId: peerHeartbeat
      produces:
        - text/plain
      parameters:
        - name: peer_id
          in: query
          description: the unique id of the client
          required: true
          type: string
      responses:
        '200':
          description: successful response
        '400':
          description: missing peer_id
externalDocs:
  - description: Find out more on Github
    url: 'https://github.com/bengreenier/webrtc-signal-http-heartbeat'
  - description: Base API
    url: 'https://github.com/bengreenier/webrtc-signal-http'